import java.util.*;

public class One {
    public static void main(String[] args) {
        String inputString = "necytxmlfhsu\n" +
                "uecosjvlhpmk\n" +
                "\n" +
                "mnslbuziphawkxyg\n" +
                "whpmnesikaglzb\n" +
                "\n" +
                "kaw\n" +
                "akw\n" +
                "\n" +
                "qurg\n" +
                "hrqug\n" +
                "qrgu\n" +
                "gruq\n" +
                "\n" +
                "sczomkv\n" +
                "zejkhvslmucbwdo\n" +
                "pxsianovzcmk\n" +
                "tcokmvsyz\n" +
                "ozskvimcr\n" +
                "\n" +
                "tfzajkxngwsqrbleic\n" +
                "tijoqnerxsplwzgabkfc\n" +
                "ogkezbiwqtaxrscljfn\n" +
                "xsqauezwnjckbtgiryfdml\n" +
                "\n" +
                "piz\n" +
                "zip\n" +
                "\n" +
                "tlp\n" +
                "npl\n" +
                "lpt\n" +
                "\n" +
                "idbnxuclqgw\n" +
                "sxfdnlatmbhcowigj\n" +
                "plzgbwdqkcinx\n" +
                "ydxinwgcblr\n" +
                "\n" +
                "nbuxjwhsrlekfyzpq\n" +
                "kecyiurjfvqpbxhzsn\n" +
                "nkxfhpbsuyrqjezom\n" +
                "tinlhkbjsuydrqpzexf\n" +
                "pnzraelgquxhydsbjkf\n" +
                "\n" +
                "obvmw\n" +
                "eoczsqun\n" +
                "\n" +
                "nhdxqwk\n" +
                "dnzmlxwhkapq\n" +
                "whxqdnk\n" +
                "\n" +
                "jnqdabgc\n" +
                "nacqdbgj\n" +
                "\n" +
                "buyskiwz\n" +
                "uazbkwys\n" +
                "\n" +
                "mbfxswpli\n" +
                "uswalhxz\n" +
                "xnq\n" +
                "tdcrjgoyekv\n" +
                "\n" +
                "fancdpkmtuqy\n" +
                "zdmenqjpaxftuy\n" +
                "\n" +
                "jkul\n" +
                "d\n" +
                "o\n" +
                "\n" +
                "vhpoxgqsrtce\n" +
                "hgopxeqcdrstv\n" +
                "xcvrqoetpsgh\n" +
                "\n" +
                "gekpzayfux\n" +
                "pyegazxukf\n" +
                "pkxaezhgyfu\n" +
                "fegypukaxz\n" +
                "zxpyefugka\n" +
                "\n" +
                "yrpfd\n" +
                "ydsh\n" +
                "\n" +
                "smjqcafnug\n" +
                "mnicqsu\n" +
                "\n" +
                "tkxi\n" +
                "ixakt\n" +
                "tfncxkmi\n" +
                "\n" +
                "kedibluzopjhagvtxf\n" +
                "afiklbvtjeoudhgpzx\n" +
                "lavbxpjzgedktoifuh\n" +
                "tbgpaxjqeoifvklhzud\n" +
                "zghidtfplxbvkoueja\n" +
                "\n" +
                "gtvnqyrmf\n" +
                "hogpb\n" +
                "\n" +
                "cnelsqwj\n" +
                "atyimdbvfxuozkg\n" +
                "\n" +
                "lgybpaeztvhrxducjiqosmnwk\n" +
                "ivpaygxweszductombhljrqk\n" +
                "\n" +
                "grli\n" +
                "lrig\n" +
                "sjglri\n" +
                "girl\n" +
                "rigl\n" +
                "\n" +
                "qnwmxjbpecoyztufidhsg\n" +
                "ynqdiwhmusgtebjfzxcpo\n" +
                "\n" +
                "luasrtmfkgywv\n" +
                "vgskmufywrat\n" +
                "\n" +
                "ceyux\n" +
                "ycux\n" +
                "\n" +
                "nurijfsovkbxdp\n" +
                "ayqclmthgzwe\n" +
                "\n" +
                "xeqjdhsubiovwrg\n" +
                "gobdjqwvusehrx\n" +
                "weqjgvhosudrbx\n" +
                "ngdubsvqxejrhow\n" +
                "\n" +
                "ywdfqpxekujbovr\n" +
                "yujfdoqbkxrepvw\n" +
                "owfkudjbvyrxqep\n" +
                "oqjvedypxukwbrf\n" +
                "xufwdpebyjrqokv\n" +
                "\n" +
                "csujqndzmw\n" +
                "wznscqmjud\n" +
                "cqpwjzmunda\n" +
                "wjumnzcqd\n" +
                "\n" +
                "dhsow\n" +
                "ohswd\n" +
                "wsnogh\n" +
                "\n" +
                "cxfltiq\n" +
                "ixztfq\n" +
                "gtfqiux\n" +
                "jtqfxi\n" +
                "xiftzq\n" +
                "\n" +
                "tr\n" +
                "rt\n" +
                "rt\n" +
                "\n" +
                "pnuztcbegwiksd\n" +
                "cuewibkptdnm\n" +
                "nvqdpcjxekiwtauhofb\n" +
                "pbytreinuwdkc\n" +
                "\n" +
                "y\n" +
                "y\n" +
                "hejq\n" +
                "\n" +
                "rvmwqn\n" +
                "wvrmq\n" +
                "\n" +
                "knxmwecsjlrft\n" +
                "hnmwzaqt\n" +
                "dmywnitg\n" +
                "tmwvquonh\n" +
                "bwqvtmnh\n" +
                "\n" +
                "e\n" +
                "e\n" +
                "e\n" +
                "\n" +
                "qjtywgdlek\n" +
                "nhifs\n" +
                "zvxinh\n" +
                "\n" +
                "nzhroemi\n" +
                "dzruoegimh\n" +
                "emzoirh\n" +
                "\n" +
                "hpfkraltbxg\n" +
                "gazxlmphrt\n" +
                "\n" +
                "jyhugbxqz\n" +
                "zbnox\n" +
                "epdilfaw\n" +
                "\n" +
                "vmr\n" +
                "vsfm\n" +
                "fmvsr\n" +
                "mnvckiaqy\n" +
                "\n" +
                "zegpfuwtkrnoqdh\n" +
                "eorznfkgpduth\n" +
                "tkfpzhnredguo\n" +
                "\n" +
                "zmqkwxipctney\n" +
                "ncwzeqpmkiytx\n" +
                "yptienwzxkcqm\n" +
                "yeqwcpxtkzmin\n" +
                "\n" +
                "csbdyzl\n" +
                "ejoiwtzqabm\n" +
                "lzbkup\n" +
                "zbvprxf\n" +
                "\n" +
                "wvpshngbmiftuzrxoyde\n" +
                "szobihvwpdtylqerc\n" +
                "phbdzoikvtajyesrw\n" +
                "\n" +
                "ymuflnrxspqvkihbe\n" +
                "eymxrhlfnqksuivbp\n" +
                "\n" +
                "rktwzd\n" +
                "wtdkzir\n" +
                "wkmaziqdrt\n" +
                "togpzwdkr\n" +
                "\n" +
                "uwiazbylcpojst\n" +
                "lcyibajuptwzso\n" +
                "\n" +
                "dtoqbcxhlyrpfwjnkasugvm\n" +
                "wunkfstmcjhqxliogrdvpy\n" +
                "\n" +
                "wpnk\n" +
                "hdpkwuftjymv\n" +
                "cpkownz\n" +
                "kpwz\n" +
                "rqpwnk\n" +
                "\n" +
                "tfplznqcju\n" +
                "puqlsnzfjtv\n" +
                "jqtfpzlun\n" +
                "ntqpczjflu\n" +
                "\n" +
                "ozalwumpqv\n" +
                "ztheoalrwsciyk\n" +
                "\n" +
                "wyiqbsr\n" +
                "bysqwri\n" +
                "yrbswiq\n" +
                "iqwrsyb\n" +
                "iwbrysq\n" +
                "\n" +
                "elnroc\n" +
                "zmjlre\n" +
                "vhelbru\n" +
                "jyhruezflvk\n" +
                "\n" +
                "ftyceboh\n" +
                "ofybh\n" +
                "\n" +
                "jvlbdm\n" +
                "noakrg\n" +
                "\n" +
                "dokjncqauebfpmszvtl\n" +
                "suebonpdjmflaqctkvz\n" +
                "dtjzmcblsvokpunaefq\n" +
                "tjzmeqkafluvpbconsd\n" +
                "\n" +
                "qhrmvegsicnyupf\n" +
                "uifknverhsg\n" +
                "izlrvgefndjwasuh\n" +
                "\n" +
                "syxvtjwfucilqogmnpk\n" +
                "jwkytpqofgimvcsnlxu\n" +
                "dwhglcxzoqnmjfkuiyvpst\n" +
                "ygwntxipqlmvkufcsoj\n" +
                "\n" +
                "hdnqaburow\n" +
                "hqwadmbocsgue\n" +
                "bwoqtuadh\n" +
                "adqhbwuo\n" +
                "\n" +
                "dzfohqe\n" +
                "ehfqzod\n" +
                "fdzhoqe\n" +
                "hdofzeq\n" +
                "\n" +
                "sxmkrghyvlwzbc\n" +
                "yhkmwzxbgsvlc\n" +
                "\n" +
                "qdumkytwlfsrja\n" +
                "drfqukzymilsjaw\n" +
                "jkwqumylsardf\n" +
                "\n" +
                "pcvs\n" +
                "prvc\n" +
                "hmbpvc\n" +
                "svrpzc\n" +
                "\n" +
                "epkjyc\n" +
                "jerpoy\n" +
                "gjpye\n" +
                "abxepuyj\n" +
                "ejyopc\n" +
                "\n" +
                "ohe\n" +
                "gheo\n" +
                "eoh\n" +
                "ofehy\n" +
                "\n" +
                "klhziowmjpyfubdsaqtgvrcn\n" +
                "aytbormdiksnqpzhcfvulgjw\n" +
                "lhmvkafdrscjgwnyiuptqobz\n" +
                "\n" +
                "vcrqpdxljnmgusie\n" +
                "cgdwmipluoe\n" +
                "\n" +
                "hqibentfmxyszljow\n" +
                "msozdjnibrfytxqhle\n" +
                "imlyxwehznjsbft\n" +
                "ysifkzbljphuxcmenvt\n" +
                "\n" +
                "vjhdmkrpecniafgqlstxyzb\n" +
                "zxjrkebfvcwyqihlsmpgtd\n" +
                "xrfzidgthsbklmveypqcj\n" +
                "vjxytzgdlbefsirkcmpqh\n" +
                "\n" +
                "dyxrwbngpijkt\n" +
                "xtwkdipaygjr\n" +
                "iklrmzwpjxgdtuye\n" +
                "pdgrxyjkitw\n" +
                "xtirhvwgdkjyp\n" +
                "\n" +
                "zbjdt\n" +
                "jdat\n" +
                "shouqjtxcd\n" +
                "\n" +
                "klarpuiv\n" +
                "iqaxjdps\n" +
                "cpnafbsi\n" +
                "\n" +
                "xfpiourcst\n" +
                "ovfrlutxpb\n" +
                "trgqfxjuop\n" +
                "rsktucfpox\n" +
                "rtufoqpx\n" +
                "\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "\n" +
                "nfutbyvj\n" +
                "umvwyi\n" +
                "\n" +
                "tjniwlydzqpsxbkcmugf\n" +
                "utpmixqdvzbfcwgljs\n" +
                "\n" +
                "wetypdlnxm\n" +
                "cfavwyzji\n" +
                "mywgu\n" +
                "lyorqkbw\n" +
                "whdeyxp\n" +
                "\n" +
                "qsbnwozepvhkmaxdrt\n" +
                "qmsopwtaznxfkehdyrv\n" +
                "xnvhwrzpemkqdtsoa\n" +
                "ituvkrhmdegazwsobnxpq\n" +
                "\n" +
                "fxhwdio\n" +
                "hofdxi\n" +
                "hivztfonxdg\n" +
                "fhkoidx\n" +
                "\n" +
                "ja\n" +
                "jca\n" +
                "ajzxt\n" +
                "ahjy\n" +
                "tajc\n" +
                "\n" +
                "epan\n" +
                "pcn\n" +
                "udn\n" +
                "\n" +
                "mfowepjdlnkags\n" +
                "oakwgflnp\n" +
                "pnlzgoawfk\n" +
                "kfgrowlnap\n" +
                "\n" +
                "uw\n" +
                "aimwo\n" +
                "wzrhcjeq\n" +
                "wtf\n" +
                "w\n" +
                "\n" +
                "x\n" +
                "tvx\n" +
                "x\n" +
                "\n" +
                "tigsjdufrwomv\n" +
                "vjrstigqudohwkm\n" +
                "visrjodutwbmg\n" +
                "\n" +
                "ety\n" +
                "exatp\n" +
                "hicfzqnb\n" +
                "uvejo\n" +
                "\n" +
                "oqlgmk\n" +
                "kgvqxd\n" +
                "jzhgkpdqy\n" +
                "ikegfwatqub\n" +
                "nlogqkz\n" +
                "\n" +
                "sl\n" +
                "q\n" +
                "\n" +
                "rkpew\n" +
                "eqrwk\n" +
                "rakwe\n" +
                "\n" +
                "r\n" +
                "r\n" +
                "r\n" +
                "rb\n" +
                "\n" +
                "u\n" +
                "pua\n" +
                "\n" +
                "pjmhtvd\n" +
                "drjnpuvib\n" +
                "djsplvy\n" +
                "dpvj\n" +
                "\n" +
                "caugyqs\n" +
                "hxwyqst\n" +
                "sougylqre\n" +
                "\n" +
                "krfshpzjmgav\n" +
                "uwrqidcotlbxhj\n" +
                "\n" +
                "mzivctbfjgwq\n" +
                "lsomkypgajiq\n" +
                "\n" +
                "ikoamrpc\n" +
                "kmociarp\n" +
                "brkmpiwycoa\n" +
                "itmckrodpa\n" +
                "kmipacro\n" +
                "\n" +
                "htbpcdqx\n" +
                "ctpbxdq\n" +
                "\n" +
                "gpduzcoiyxhleqrknbaw\n" +
                "nirehbulapcoxkzwdy\n" +
                "icuzyxopwhkalendrb\n" +
                "aokdrxhlcebpyiuwnz\n" +
                "\n" +
                "yzlvptdaubjerkh\n" +
                "iyaoltghebpndkjszr\n" +
                "kqxjtldzpbcyawh\n" +
                "dbjtlavzmfhkyp\n" +
                "\n" +
                "vg\n" +
                "sv\n" +
                "\n" +
                "cdiaynroehqw\n" +
                "cqtaridyohewn\n" +
                "dciornehwayq\n" +
                "rwhnoaeqicdy\n" +
                "wqroadniechy\n" +
                "\n" +
                "ivstkj\n" +
                "vgciqk\n" +
                "qkivg\n" +
                "vkgi\n" +
                "\n" +
                "fp\n" +
                "pf\n" +
                "pf\n" +
                "fp\n" +
                "fp\n" +
                "\n" +
                "xidyqnk\n" +
                "jbicfant\n" +
                "zabfhin\n" +
                "\n" +
                "oqtys\n" +
                "stqyo\n" +
                "syqot\n" +
                "yostq\n" +
                "boqytws\n" +
                "\n" +
                "gmnqxaictud\n" +
                "tucidaxqnmg\n" +
                "pgtquxidcnma\n" +
                "iagdtcfmquxn\n" +
                "\n" +
                "yfhxgw\n" +
                "rgn\n" +
                "nsog\n" +
                "\n" +
                "wndrqktbmfa\n" +
                "fwqadkrtbnm\n" +
                "mabfntkqword\n" +
                "qbwntakrmdf\n" +
                "\n" +
                "elanoudxhbzfrtvci\n" +
                "ztalefiodxrubvckhn\n" +
                "ulvabcnthpdzxoifer\n" +
                "\n" +
                "omdrvepliwafhjynbscu\n" +
                "mblrxjsfahocwnvyu\n" +
                "umcjlsowatvnfybhr\n" +
                "uahvcnbwlmsjzfoyr\n" +
                "\n" +
                "n\n" +
                "tn\n" +
                "n\n" +
                "\n" +
                "grk\n" +
                "rgk\n" +
                "krg\n" +
                "gkr\n" +
                "rgkhv\n" +
                "\n" +
                "stmlnek\n" +
                "pgsltne\n" +
                "\n" +
                "alcztk\n" +
                "bctvk\n" +
                "khcgtb\n" +
                "\n" +
                "nsgevcthrpykbwfoizda\n" +
                "khneritgszvbfycaowdp\n" +
                "ivybwzeaogdsrnfctphk\n" +
                "\n" +
                "e\n" +
                "e\n" +
                "e\n" +
                "\n" +
                "cxkzdbgiqyawnm\n" +
                "afyvkbeirtjowmcl\n" +
                "\n" +
                "omb\n" +
                "p\n" +
                "\n" +
                "lnhwcoiyafs\n" +
                "soihnyxqfc\n" +
                "ohncjyifsq\n" +
                "\n" +
                "o\n" +
                "o\n" +
                "om\n" +
                "oxqnsd\n" +
                "oaj\n" +
                "\n" +
                "okucjhiq\n" +
                "xpgwcnqjiomyfluk\n" +
                "irhoukdsbjqc\n" +
                "\n" +
                "uolgz\n" +
                "nglczu\n" +
                "zlngu\n" +
                "zmhlgvjru\n" +
                "\n" +
                "mhdapszf\n" +
                "anmfwdvkc\n" +
                "dpamf\n" +
                "\n" +
                "aqleivtyzsogjc\n" +
                "syvbgxqpdflezoac\n" +
                "ilvzqsjaegokyc\n" +
                "\n" +
                "zxndhja\n" +
                "haxzd\n" +
                "xhazd\n" +
                "\n" +
                "mo\n" +
                "om\n" +
                "mo\n" +
                "mo\n" +
                "\n" +
                "vfxep\n" +
                "xfepv\n" +
                "xevpf\n" +
                "vexfp\n" +
                "pevfx\n" +
                "\n" +
                "mrtkehqnjxizgp\n" +
                "kbunrqytcmes\n" +
                "\n" +
                "nz\n" +
                "ipneu\n" +
                "\n" +
                "bznteo\n" +
                "tbzeoqwp\n" +
                "olftzbpk\n" +
                "grzvityxudohjma\n" +
                "\n" +
                "xg\n" +
                "rg\n" +
                "\n" +
                "rdu\n" +
                "urvd\n" +
                "rud\n" +
                "rzud\n" +
                "\n" +
                "somnbutz\n" +
                "tuosnmb\n" +
                "ntomsbu\n" +
                "\n" +
                "fxsvrzqntbueoyp\n" +
                "eqzsvxyunbroptf\n" +
                "zvypnrxfsqebuot\n" +
                "zrosbxeqpunvfty\n" +
                "zprtfvsnbquexoy\n" +
                "\n" +
                "qwzknfvl\n" +
                "funqlwkj\n" +
                "nqkwflz\n" +
                "fgxlkwzqn\n" +
                "\n" +
                "rzqihd\n" +
                "rbz\n" +
                "zr\n" +
                "uzer\n" +
                "rbz\n" +
                "\n" +
                "utrq\n" +
                "osa\n" +
                "pm\n" +
                "\n" +
                "zgdci\n" +
                "brhu\n" +
                "\n" +
                "bxvymlzqkpha\n" +
                "vmhlakpyxq\n" +
                "ypxvqkmhal\n" +
                "xhvpymaqkl\n" +
                "aplqvkhmyx\n" +
                "\n" +
                "sjntbvyogeplwzu\n" +
                "rbjqiefhapxodwk\n" +
                "\n" +
                "frlsoptqwbc\n" +
                "ljrzxqntfom\n" +
                "\n" +
                "zlhvjamtpfonk\n" +
                "lcokjzdhmfvnp\n" +
                "siohzynkmbjvlrf\n" +
                "\n" +
                "osvgwnticelpzm\n" +
                "jvswetpozlcg\n" +
                "\n" +
                "npmgrvysfj\n" +
                "nvqxrjfsgmp\n" +
                "vofthkcjsblpmudizwr\n" +
                "\n" +
                "oiev\n" +
                "lmeiov\n" +
                "oiezyv\n" +
                "uievodkac\n" +
                "\n" +
                "iforupqjzykdtc\n" +
                "yqfhdcxvtopz\n" +
                "tzqpfdycgo\n" +
                "ceyqfozvtpd\n" +
                "dpxqflohzyatc\n" +
                "\n" +
                "srz\n" +
                "zsrt\n" +
                "strz\n" +
                "xzs\n" +
                "sz\n" +
                "\n" +
                "dgo\n" +
                "odg\n" +
                "ogd\n" +
                "dog\n" +
                "qogd\n" +
                "\n" +
                "gotwqhick\n" +
                "okhqtgicw\n" +
                "gsouwitkjcqh\n" +
                "hctgioqwk\n" +
                "tkghocwiq\n" +
                "\n" +
                "mfnziwvxtlpubqryojasd\n" +
                "mzojuctvnbriypwflskqda\n" +
                "pmuavqjifnlhrtbyzwods\n" +
                "\n" +
                "ozj\n" +
                "joz\n" +
                "zjo\n" +
                "jzo\n" +
                "\n" +
                "jzwbhrscm\n" +
                "rzmhjctb\n" +
                "zbrhcmj\n" +
                "\n" +
                "sucgimtr\n" +
                "myliojcrsg\n" +
                "ipcsegxrmv\n" +
                "\n" +
                "znhvi\n" +
                "hvin\n" +
                "wosganie\n" +
                "\n" +
                "wptoqxmafhg\n" +
                "awqfhgcozmtx\n" +
                "\n" +
                "azbqlviyrwjc\n" +
                "ybxcrawv\n" +
                "\n" +
                "qa\n" +
                "vcuwbfgsl\n" +
                "hkraj\n" +
                "\n" +
                "biglkjtpoqs\n" +
                "zvxcfumeywrhand\n" +
                "\n" +
                "ske\n" +
                "s\n" +
                "sp\n" +
                "hs\n" +
                "\n" +
                "n\n" +
                "yn\n" +
                "n\n" +
                "n\n" +
                "n\n" +
                "\n" +
                "lrvsmxzkgi\n" +
                "zgrmkdsxl\n" +
                "lzgmpakrs\n" +
                "wgqtrkmsfz\n" +
                "nirmkugzds\n" +
                "\n" +
                "crewvjdqsplkibthxz\n" +
                "wxjmtpirhalqsckbdz\n" +
                "\n" +
                "iecxrbplho\n" +
                "xhrpibovlce\n" +
                "brxlgchopei\n" +
                "cbhioprexln\n" +
                "lchxirebop\n" +
                "\n" +
                "f\n" +
                "f\n" +
                "q\n" +
                "\n" +
                "nxqkrhdi\n" +
                "pkhdrquxn\n" +
                "ynqdlxkh\n" +
                "xghkndq\n" +
                "\n" +
                "wvknrdjx\n" +
                "vknxrwdm\n" +
                "kfvicpwndb\n" +
                "\n" +
                "rcqwlutsanpdz\n" +
                "yoxenmkvbjf\n" +
                "\n" +
                "izqsa\n" +
                "sqzai\n" +
                "zqsai\n" +
                "osiazq\n" +
                "izqsa\n" +
                "\n" +
                "ysokhbpzcqanmdifw\n" +
                "kdlowyusmqhbjxci\n" +
                "hibkmzocndqswy\n" +
                "\n" +
                "yjwd\n" +
                "bgas\n" +
                "yj\n" +
                "k\n" +
                "\n" +
                "tzruq\n" +
                "uorz\n" +
                "zckrvux\n" +
                "\n" +
                "rjn\n" +
                "nrj\n" +
                "nrj\n" +
                "jrn\n" +
                "njr\n" +
                "\n" +
                "ecu\n" +
                "pzus\n" +
                "wokxu\n" +
                "ruw\n" +
                "twu\n" +
                "\n" +
                "fcnajztduyripl\n" +
                "chmpkvlynsxrauobji\n" +
                "\n" +
                "cwfgtjre\n" +
                "ejwufr\n" +
                "frwje\n" +
                "newvryfjbhq\n" +
                "iwjextrf\n" +
                "\n" +
                "ltqapiwhzfeoncxdg\n" +
                "hndclgoxeiwtpqfz\n" +
                "cwnpdogxteilfqhz\n" +
                "\n" +
                "uerinxhsygpbzcdvfmo\n" +
                "lxeihducozgqnrymb\n" +
                "edmugnyxifoczrbha\n" +
                "ucezhnrsdybmiotgx\n" +
                "\n" +
                "xuvfhjeyi\n" +
                "ztcgaqs\n" +
                "\n" +
                "yxrospmijwvcdb\n" +
                "yjpbrcosuv\n" +
                "\n" +
                "viuhdrgnlak\n" +
                "lniaruvkdgh\n" +
                "khrgdnuiavl\n" +
                "\n" +
                "qfzxb\n" +
                "gfqx\n" +
                "\n" +
                "k\n" +
                "nzyo\n" +
                "kcj\n" +
                "\n" +
                "bmi\n" +
                "bmi\n" +
                "imb\n" +
                "imb\n" +
                "ubmi\n" +
                "\n" +
                "pl\n" +
                "pl\n" +
                "pl\n" +
                "lp\n" +
                "\n" +
                "x\n" +
                "v\n" +
                "x\n" +
                "\n" +
                "hgwtocs\n" +
                "gdctwhoi\n" +
                "iczwfgtoxh\n" +
                "\n" +
                "wrcjdaqm\n" +
                "wsrlog\n" +
                "jrnqmcw\n" +
                "\n" +
                "ouhmpnyskxcqafidbjvgt\n" +
                "dnimvbpytfsoagucjx\n" +
                "jpctsmuxiaovyqnfdbg\n" +
                "gzbvfwmojuyxsrdtpcna\n" +
                "yxfolphstnabcmuvjgd\n" +
                "\n" +
                "nlrdxe\n" +
                "ceksxuhazmjo\n" +
                "ywxedfgqtpr\n" +
                "\n" +
                "ckuwoghtaxrledvzms\n" +
                "mtksozduwvrehxclag\n" +
                "xwvcusrmlazoetkdgh\n" +
                "regwvshxkdzuctomal\n" +
                "\n" +
                "khsnymbpjz\n" +
                "hzknspmbj\n" +
                "\n" +
                "zqc\n" +
                "kpgsjrqxiyd\n" +
                "wtbuhoq\n" +
                "qwc\n" +
                "eq\n" +
                "\n" +
                "ljewzy\n" +
                "qlwjy\n" +
                "wzljy\n" +
                "lwyj\n" +
                "ljwy\n" +
                "\n" +
                "vpodmhni\n" +
                "bvryknfg\n" +
                "jcutez\n" +
                "\n" +
                "wedfcoh\n" +
                "wigfnjkaoz\n" +
                "exwoqfm\n" +
                "pfuohsw\n" +
                "\n" +
                "adyzjwgqxv\n" +
                "qjwvxzagyd\n" +
                "\n" +
                "cazpofbyd\n" +
                "nodypfbcam\n" +
                "\n" +
                "ukvrcslyqzamhteowdfibx\n" +
                "ktrgqpmnawdycsivhzlbefx\n" +
                "fxdabuylcveksjwrmzqhtio\n" +
                "\n" +
                "xyb\n" +
                "xesy\n" +
                "xdqcy\n" +
                "yex\n" +
                "xy\n" +
                "\n" +
                "hotd\n" +
                "odhzqt\n" +
                "othd\n" +
                "htod\n" +
                "\n" +
                "hvkc\n" +
                "lzei\n" +
                "asw\n" +
                "a\n" +
                "d\n" +
                "\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "q\n" +
                "\n" +
                "a\n" +
                "a\n" +
                "a\n" +
                "\n" +
                "suqbvedipgzcjykfmaxno\n" +
                "jzfudeoxikpbvmgynsha\n" +
                "iswkepmodzvfgxnylujba\n" +
                "\n" +
                "xpqjonkzlrfhtyw\n" +
                "fjqksrlozypwnmxth\n" +
                "pkrohjnxlfzyqtw\n" +
                "\n" +
                "pxuhsc\n" +
                "hcxsnu\n" +
                "hxcse\n" +
                "cxhws\n" +
                "hcrsex\n" +
                "\n" +
                "iglfosahy\n" +
                "hizgfalodbs\n" +
                "lgfoiahs\n" +
                "gsfalhyio\n" +
                "\n" +
                "xrgzwbdnohfeijacsmltqp\n" +
                "djpgqrimtwcafsxnlebzoh\n" +
                "\n" +
                "qlrn\n" +
                "qrn\n" +
                "qrn\n" +
                "qrn\n" +
                "\n" +
                "xhbiakuzcjm\n" +
                "nfpykow\n" +
                "klfs\n" +
                "\n" +
                "lcubkpfhnomgwyarjetqd\n" +
                "wtcrgofdnlpbaykquevhj\n" +
                "\n" +
                "bdqusvnyetklmwizcopxjr\n" +
                "drbxlptyeqcvjwiusmzokn\n" +
                "oqcjzvuwslkpedbxmrntyi\n" +
                "jvlnxtdpkusyczbeomqirw\n" +
                "wltriuqnpzcxbysvojdmek\n" +
                "\n" +
                "tyeorbzjdxpqn\n" +
                "oprlqdnwbzyx\n" +
                "brnydoqzxp\n" +
                "\n" +
                "bupvcrylqazehoknjtf\n" +
                "aqfroczbylpvuejk\n" +
                "ubqvelyfrzoxcpagkj\n" +
                "\n" +
                "awbzx\n" +
                "axuw\n" +
                "ywildxoa\n" +
                "uwxnba\n" +
                "\n" +
                "mjfvro\n" +
                "wmrfjov\n" +
                "ojvmursf\n" +
                "\n" +
                "zwxouqy\n" +
                "ouzyw\n" +
                "\n" +
                "dsxf\n" +
                "sfdti\n" +
                "syrfd\n" +
                "\n" +
                "zmibfjk\n" +
                "kimbz\n" +
                "\n" +
                "nebq\n" +
                "beqn\n" +
                "eqnb\n" +
                "bqnpe\n" +
                "\n" +
                "avtnckldjpeys\n" +
                "scjtklpdneyav\n" +
                "kytncdpsvaelj\n" +
                "tkpacjysdnvle\n" +
                "dycsvtjplenak\n" +
                "\n" +
                "mkyojv\n" +
                "biwro\n" +
                "botsx\n" +
                "\n" +
                "owxyu\n" +
                "wyuxo\n" +
                "yxwuo\n" +
                "\n" +
                "qgjplcvo\n" +
                "vgjqocpl\n" +
                "ojvlcpgq\n" +
                "\n" +
                "xczvkuohisrfqbagp\n" +
                "prbeilfzognvqws\n" +
                "voitfqpgjmrzsb\n" +
                "rvlfdoqigsbpz\n" +
                "ipqogbrzfmsv\n" +
                "\n" +
                "j\n" +
                "s\n" +
                "st\n" +
                "t\n" +
                "pzde\n" +
                "\n" +
                "kuwbthejxcfrzgosmn\n" +
                "xwcukhrtsgzf\n" +
                "tkfcguxwshrz\n" +
                "hxukfzgdwsrqict\n" +
                "zwucgkfqhvxtrs\n" +
                "\n" +
                "wvthikzpgrjaf\n" +
                "swdnemkqobcyx\n" +
                "\n" +
                "lewoquaprbkxyj\n" +
                "xpelwoaksubcrhqd\n" +
                "gbrxmluktiwnaopqe\n" +
                "epxuyczokafblwjrq\n" +
                "\n" +
                "mcyepsvwxr\n" +
                "bhe\n" +
                "nqeztgd\n" +
                "uaehil\n" +
                "\n" +
                "tq\n" +
                "be\n" +
                "e\n" +
                "\n" +
                "duqgair\n" +
                "dfrwuiqga\n" +
                "qaugidr\n" +
                "\n" +
                "hmofng\n" +
                "hgnomf\n" +
                "mofghn\n" +
                "gmotfhn\n" +
                "\n" +
                "ewhblqnsmjict\n" +
                "whmbxvpjs\n" +
                "ufzyaogdkr\n" +
                "\n" +
                "jqpynazsfvklied\n" +
                "sjilykvqza\n" +
                "izsvjlqayk\n" +
                "qiksvzlajy\n" +
                "\n" +
                "vbps\n" +
                "vbstp\n" +
                "evnigorks\n" +
                "vbst\n" +
                "jslv\n" +
                "\n" +
                "qgdzylwkbfou\n" +
                "jbwygulq\n" +
                "qwhxrugpeb\n" +
                "giqdfvbwu\n" +
                "\n" +
                "jubto\n" +
                "aeuvgdpx\n" +
                "unl\n" +
                "yorqui\n" +
                "uqm\n" +
                "\n" +
                "ic\n" +
                "kci\n" +
                "a\n" +
                "i\n" +
                "gyfe\n" +
                "\n" +
                "tjxp\n" +
                "xtj\n" +
                "xjt\n" +
                "\n" +
                "ldspeai\n" +
                "eapidul\n" +
                "peiadl\n" +
                "ipelad\n" +
                "\n" +
                "oymwvfriux\n" +
                "moxuywvfir\n" +
                "rmvxwoujifyb\n" +
                "fpvwdumgyroxzi\n" +
                "\n" +
                "mcplvnkgjfz\n" +
                "idszwngkfcvpl\n" +
                "njzfklgcpvo\n" +
                "fcvokpnlzg\n" +
                "\n" +
                "xdnsilr\n" +
                "irnlsx\n" +
                "\n" +
                "bndvimefz\n" +
                "atopdu\n" +
                "xhswykcqgrjl\n" +
                "\n" +
                "kvlorsye\n" +
                "\n" +
                "vsdoq\n" +
                "dvos\n" +
                "vodjs\n" +
                "\n" +
                "bxczyfeajkmloi\n" +
                "jcimfkaloybxze\n" +
                "ceijaokfzyxmlb\n" +
                "feymoacbjxikzl\n" +
                "kcxmiebzyaoljf\n" +
                "\n" +
                "lo\n" +
                "ol\n" +
                "\n" +
                "etxkfsgjlqoy\n" +
                "fgshieyj\n" +
                "esywfgj\n" +
                "gwrjsyepf\n" +
                "\n" +
                "jtzlgakxins\n" +
                "gqlznxfabskijp\n" +
                "ikaxgsnzljh\n" +
                "lgaizhkjxns\n" +
                "hgaznkjxtlis\n" +
                "\n" +
                "urhjiycw\n" +
                "rhycisw\n" +
                "zrwihkcy\n" +
                "\n" +
                "xc\n" +
                "cvx\n" +
                "cx\n" +
                "cxgl\n" +
                "\n" +
                "audxneqrchg\n" +
                "efkmodwqplrzsiyb\n" +
                "\n" +
                "g\n" +
                "x\n" +
                "x\n" +
                "\n" +
                "ziuplaqo\n" +
                "czqtihuw\n" +
                "zufiq\n" +
                "nqzubpixak\n" +
                "\n" +
                "cibdku\n" +
                "dbckiu\n" +
                "kdciub\n" +
                "\n" +
                "eshpjzgtwrka\n" +
                "tgwpafmsjkrehz\n" +
                "sekbwtnxjhpzrag\n" +
                "\n" +
                "dj\n" +
                "dm\n" +
                "dj\n" +
                "\n" +
                "trqkdpwoxjfyg\n" +
                "csu\n" +
                "ancv\n" +
                "lui\n" +
                "ebhmaz\n" +
                "\n" +
                "ljbvexnhgwfs\n" +
                "hfjbxneyilwgu\n" +
                "znejqblcdhfgwx\n" +
                "\n" +
                "b\n" +
                "b\n" +
                "b\n" +
                "b\n" +
                "b\n" +
                "\n" +
                "idxrcyjegnu\n" +
                "lrhvskceg\n" +
                "rozwmgafbce\n" +
                "\n" +
                "gzasrwjlukomvdxhbpc\n" +
                "cahmgzurlvpwxbdjs\n" +
                "uxjzsbgmdlchvprwa\n" +
                "hramvdjxslubpzgcw\n" +
                "\n" +
                "gw\n" +
                "wge\n" +
                "\n" +
                "fpgdzy\n" +
                "wpfdbz\n" +
                "zpfahde\n" +
                "lfdpszcorx\n" +
                "zfdgbqpha\n" +
                "\n" +
                "gfuclekqavitdxr\n" +
                "euwkvdirqtcxa\n" +
                "riuxvaqkcdte\n" +
                "\n" +
                "eqaphotimfdrukcgwbyx\n" +
                "dxtowkygamibqcrfeuhp\n" +
                "oiutpbavhdyqergfcmxws\n" +
                "ahcteowdfrkugpibqjymx\n" +
                "\n" +
                "pmixjle\n" +
                "uxljemp\n" +
                "lkpsej\n" +
                "\n" +
                "mzqcwxuo\n" +
                "xoucwzmq\n" +
                "xcumzqsow\n" +
                "zcuqxmwo\n" +
                "\n" +
                "wt\n" +
                "wt\n" +
                "\n" +
                "tyrajn\n" +
                "hdtgroynjae\n" +
                "jrnyat\n" +
                "\n" +
                "uqifnlv\n" +
                "iqnevl\n" +
                "vqienl\n" +
                "navciql\n" +
                "\n" +
                "qjxpshtuzbmfnvogcalw\n" +
                "skvzqthufxcjeagrmdiwlyb\n" +
                "\n" +
                "lvaftw\n" +
                "vkfaywtl\n" +
                "lfvawtq\n" +
                "\n" +
                "wpusqdfkybg\n" +
                "mghtdxkpsur\n" +
                "dsgxhumpk\n" +
                "jmdkpzrsixug\n" +
                "\n" +
                "qcbalvykixze\n" +
                "fmrhcsadlnio\n" +
                "cpautjihl\n" +
                "clgainupm\n" +
                "ilcaft\n" +
                "\n" +
                "pklutwg\n" +
                "gdpkrl\n" +
                "lrpkg\n" +
                "\n" +
                "wbup\n" +
                "bygfurw\n" +
                "ubw\n" +
                "\n" +
                "xsoqjceyhunvat\n" +
                "jshgokqucxvlyn\n" +
                "\n" +
                "pyk\n" +
                "pyk\n" +
                "\n" +
                "l\n" +
                "s\n" +
                "\n" +
                "m\n" +
                "m\n" +
                "hm\n" +
                "\n" +
                "msultwhivz\n" +
                "vzitlhwmus\n" +
                "htsmluvzwi\n" +
                "ihszwmvult\n" +
                "iwthzsumvl\n" +
                "\n" +
                "wlohkegqpb\n" +
                "jzguytqrncd\n" +
                "igqvesfa\n" +
                "\n" +
                "h\n" +
                "hgy\n" +
                "\n" +
                "xb\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "\n" +
                "ij\n" +
                "ji\n" +
                "hqdl\n" +
                "\n" +
                "k\n" +
                "k\n" +
                "fkswyr\n" +
                "zk\n" +
                "\n" +
                "frvpln\n" +
                "vfcnlpr\n" +
                "vfnrlp\n" +
                "rnpvfl\n" +
                "\n" +
                "ouy\n" +
                "yu\n" +
                "uy\n" +
                "yu\n" +
                "yug\n" +
                "\n" +
                "rhekb\n" +
                "etnxfymlgdwovqzu\n" +
                "csbheji\n" +
                "beca\n" +
                "\n" +
                "vj\n" +
                "nfpv\n" +
                "v\n" +
                "v\n" +
                "\n" +
                "ruvqehmija\n" +
                "mdhjqrayuie\n" +
                "ksqrfgjeihpmlu\n" +
                "\n" +
                "kbsnlqxfrizjauthodp\n" +
                "uxdjbqniholafzrskt\n" +
                "eaokjungrdfshlbtzqix\n" +
                "wjlsbciontzkdqfxhuar\n" +
                "qjlosubzkfitnahrdx\n" +
                "\n" +
                "sbzcefm\n" +
                "zsmb\n" +
                "szmb\n" +
                "mszb\n" +
                "smzb\n" +
                "\n" +
                "xzisbpmc\n" +
                "prihnxstmfzb\n" +
                "klpbmszijxw\n" +
                "vmepbiszxaq\n" +
                "zipmjbxvs\n" +
                "\n" +
                "qjgbnvamedwi\n" +
                "qajzdoksweb\n" +
                "\n" +
                "gtkfqwlzashcen\n" +
                "geiqzsnhkfwctv\n" +
                "esnmhfzgqutpwyk\n" +
                "igselxqndbfwthkz\n" +
                "\n" +
                "obpdyswkvthxgreanmjluq\n" +
                "lahobnkyxtdrqgseuvcj\n" +
                "\n" +
                "pw\n" +
                "wpe\n" +
                "ylp\n" +
                "ep\n" +
                "\n" +
                "owrlgniy\n" +
                "iljkvwxyhopufzsqdc\n" +
                "\n" +
                "wxzgdpt\n" +
                "saxprdtkf\n" +
                "qdxjotpgbwl\n" +
                "xtdhjpl\n" +
                "utdjphxci\n" +
                "\n" +
                "gwkrjnizdxbvc\n" +
                "hfnpygvaw\n" +
                "ygvutnaw\n" +
                "\n" +
                "pecfzghqxturdijsblmk\n" +
                "klsxuqpfhdbctrjgemzi\n" +
                "dtuzljfxhmbgciqkeprs\n" +
                "\n" +
                "iznfycwdrh\n" +
                "zwnrchiydf\n" +
                "\n" +
                "xutwndim\n" +
                "osidj\n" +
                "\n" +
                "knwyjicb\n" +
                "jc\n" +
                "zjgc\n" +
                "cju\n" +
                "\n" +
                "jwtep\n" +
                "hjer\n" +
                "egj\n" +
                "\n" +
                "khwsitfnxyep\n" +
                "iwkpnxeh\n" +
                "wephiklnx\n" +
                "hcigwzkapxremn\n" +
                "nwehmapkxib\n" +
                "\n" +
                "vuqbmineogja\n" +
                "dlrpainmvugj\n" +
                "ravsmgijfcuhynt\n" +
                "awvpiunjmg\n" +
                "\n" +
                "zdcalubhniv\n" +
                "nclhvibudaz\n" +
                "vhcdbuznila\n" +
                "\n" +
                "bzcaorhqflg\n" +
                "jteyvpwsuxdnik\n" +
                "\n" +
                "icr\n" +
                "rvic\n" +
                "cri\n" +
                "ric\n" +
                "ric\n" +
                "\n" +
                "bqikw\n" +
                "ibwqk\n" +
                "\n" +
                "ipxdcvmfulwejyg\n" +
                "nqcelgydaskrxhi\n" +
                "\n" +
                "pkovrgdljyh\n" +
                "vq\n" +
                "ixwv\n" +
                "vsxaczn\n" +
                "\n" +
                "ix\n" +
                "xi\n" +
                "ix\n" +
                "\n" +
                "hkxl\n" +
                "hklx\n" +
                "uxlkcsvgeh\n" +
                "khlyjx\n" +
                "blkxh\n" +
                "\n" +
                "lhgcae\n" +
                "yczfas\n" +
                "conasulj\n" +
                "xgbflezcuayo\n" +
                "mvcidtapr\n" +
                "\n" +
                "iwaepxckbvjnzmqft\n" +
                "pwiancxtmufqsvzj\n" +
                "cpanmiftxjwqzv\n" +
                "mhftvjnxzpowciqa\n" +
                "\n" +
                "ir\n" +
                "rd\n" +
                "ir\n" +
                "\n" +
                "xt\n" +
                "xt\n" +
                "tx\n" +
                "xtk\n" +
                "tx\n" +
                "\n" +
                "rdatjzibwsu\n" +
                "mdsuarwtizjb\n" +
                "\n" +
                "rselwj\n" +
                "wetbjy\n" +
                "pzxqjowe\n" +
                "njtgbvwmei\n" +
                "\n" +
                "qgcazvn\n" +
                "gqsvcnz\n" +
                "vczgqn\n" +
                "\n" +
                "vmufbi\n" +
                "efuinvmq\n" +
                "uicgmkvr\n" +
                "vnmilu\n" +
                "ubvwmix\n" +
                "\n" +
                "lseymvjuidhkoptazcxrw\n" +
                "wnbsukhpjoedczrlavgtmf\n" +
                "scmrptkhdeazojwvquly\n" +
                "\n" +
                "qopb\n" +
                "evwqyl\n" +
                "\n" +
                "syuzojncfrliwap\n" +
                "wnocfplirjzsa\n" +
                "izwrhvftqbdgpcjoasln\n" +
                "ljiznraspxofwc\n" +
                "rzcpanjowslif\n" +
                "\n" +
                "lpebrhxtam\n" +
                "iyuvknwfso\n" +
                "\n" +
                "by\n" +
                "yb\n" +
                "\n" +
                "qshtypdlocawvgjb\n" +
                "xvyrnwfqezshjoka\n" +
                "\n" +
                "xhw\n" +
                "nwhx\n" +
                "hwx\n" +
                "whsex\n" +
                "\n" +
                "xelcghsquwivjydnrzkbfpa\n" +
                "elviwcpnsokhjqubgadxyzfr\n" +
                "dcfqxvneymsutzkrlpgbjiwah\n" +
                "\n" +
                "ghckb\n" +
                "bgh\n" +
                "\n" +
                "rdojuvqncia\n" +
                "nracovyiw\n" +
                "cvryoina\n" +
                "echariovn\n" +
                "\n" +
                "rjmdqahvbplcusigfx\n" +
                "cluaqvsfhmrjbpgidx\n" +
                "gvchlipxjsaufrbqdm\n" +
                "pjdsqmvlcaubfirhxg\n" +
                "\n" +
                "tngbc\n" +
                "btcng\n" +
                "nbgct\n" +
                "bcgnt\n" +
                "\n" +
                "aonpsbqkhwclrmdyuz\n" +
                "mcgubhqdokarzlspnwy\n" +
                "olhybcuasmrdzqwnkp\n" +
                "lkshamocyrdznwuqbp\n" +
                "wlunozascybqprmhkd\n" +
                "\n" +
                "skilqth\n" +
                "qhlts\n" +
                "uslvqt\n" +
                "fqstl\n" +
                "ftshql\n" +
                "\n" +
                "fbtxdirelcsqzu\n" +
                "icsyjfltxdeurq\n" +
                "rueptfdcqylixs\n" +
                "usqtxfdrclei\n" +
                "lwqdvtxeirsfucna\n" +
                "\n" +
                "xphvrbl\n" +
                "bthixl\n" +
                "wqjmohcfxyazlsb\n" +
                "vhluxb\n" +
                "\n" +
                "kbnogjrhe\n" +
                "krbngeohj\n" +
                "hnekjbrog\n" +
                "rkbeognjh\n" +
                "kjrohebng\n" +
                "\n" +
                "z\n" +
                "yzn\n" +
                "\n" +
                "wslprjfqa\n" +
                "regwpyqdksaci\n" +
                "\n" +
                "glmkujvbatqwc\n" +
                "mtubqgclavrjwk\n" +
                "wuqmjlgcabvtk\n" +
                "galuqbvctmkjw\n" +
                "ckblwqujgvmat\n" +
                "\n" +
                "kgrmfstlejw\n" +
                "bdithoauynzpv\n" +
                "\n" +
                "wvyzhfdistmqkrugx\n" +
                "nzlspqermfwjahui\n" +
                "ufqsipwozmhr\n" +
                "\n" +
                "fdsavukrbpcm\n" +
                "zrasokjlvudmpbf\n" +
                "eqvbkfrswpdtumag\n" +
                "dmhkfplvbarnus\n" +
                "\n" +
                "tdorlvb\n" +
                "pvdhiko\n" +
                "omgsjwuavycxe\n" +
                "pziqbovhnf\n" +
                "\n" +
                "f\n" +
                "a\n" +
                "u\n" +
                "u\n" +
                "u\n" +
                "\n" +
                "efg\n" +
                "egf\n" +
                "feg\n" +
                "fge\n" +
                "\n" +
                "wsf\n" +
                "lmcd\n" +
                "f\n" +
                "v\n" +
                "ve\n" +
                "\n" +
                "mibscvfqnhoxty\n" +
                "rxphcsiqbofvnw\n" +
                "uexoibzljkqagcnf\n" +
                "\n" +
                "sbmhgyqvkuoljzwrfnxietca\n" +
                "ocjebltaqwursipnfkmx\n" +
                "\n" +
                "xeh\n" +
                "unxmh\n" +
                "\n" +
                "du\n" +
                "ud\n" +
                "ud\n" +
                "du\n" +
                "\n" +
                "tvzo\n" +
                "vo\n" +
                "ovft\n" +
                "vto\n" +
                "povdq\n" +
                "\n" +
                "r\n" +
                "s\n" +
                "lhibgo\n" +
                "qny\n" +
                "nwk\n" +
                "\n" +
                "cwxfhrgjdsyamtkv\n" +
                "fshogpwdinlrcjexmt\n" +
                "yxvdtzfrsgmcjqwbh\n" +
                "\n" +
                "zil\n" +
                "liz\n" +
                "liz\n" +
                "\n" +
                "iygvphrujkwaxl\n" +
                "ikjyutlxawvgrph\n" +
                "hvuliyrdjakwpxg\n" +
                "rjthkylwipxgvuad\n" +
                "wivxkhlausgpjyr\n" +
                "\n" +
                "vrxkaqzgmsyon\n" +
                "vorxcumswqznyag\n" +
                "\n" +
                "vlhuwzmdq\n" +
                "bsoryk\n" +
                "yeka\n" +
                "\n" +
                "eiqwuz\n" +
                "uvwznpqikr\n" +
                "wluozi\n" +
                "xjbyizufsagdtwm\n" +
                "wzhuic\n" +
                "\n" +
                "wydkjlfzpeqtgxorhmnuci\n" +
                "tuczlfqrdnyxihgjopkwem\n" +
                "tdpylmxcibgkfhjzwerasnou\n" +
                "zelpcrdoygnxjvfmktuhwi\n" +
                "gwmehyiojukcnfxrptzdl\n" +
                "\n" +
                "vcuizfrlhqa\n" +
                "rvizlucafhqj\n" +
                "cviluqfhraz\n" +
                "\n" +
                "wmgu\n" +
                "ve\n" +
                "sgly\n" +
                "fmwx\n" +
                "\n" +
                "ke\n" +
                "ek\n" +
                "\n" +
                "elhq\n" +
                "hqel\n" +
                "qehl\n" +
                "ehql\n" +
                "\n" +
                "hzdfnwxtjysrio\n" +
                "mykgu\n" +
                "vy\n" +
                "kpmaqy\n" +
                "gbeykc\n" +
                "\n" +
                "pfkj\n" +
                "hfkpj\n" +
                "kpfj\n" +
                "pfjk\n" +
                "kpfjd\n" +
                "\n" +
                "z\n" +
                "t\n" +
                "z\n" +
                "t\n" +
                "oxy\n" +
                "\n" +
                "ux\n" +
                "auhzoj\n" +
                "xu\n" +
                "u\n" +
                "\n" +
                "gcaldiph\n" +
                "lhnfapi\n" +
                "\n" +
                "slg\n" +
                "slg\n" +
                "lgs\n" +
                "lgs\n" +
                "sgl\n" +
                "\n" +
                "h\n" +
                "h\n" +
                "h\n" +
                "\n" +
                "qodwxpmskvjbtycuzghfe\n" +
                "pesjgxqzbtdcoyhwmu\n" +
                "ylthszqpuwebodxmgcj\n" +
                "chqjetzxgdyopbwmuls\n" +
                "\n" +
                "fkgtmuyoivdehpjcxsba\n" +
                "agycjmdsfirvkuowtpbhex\n" +
                "\n" +
                "ocaw\n" +
                "msclaw\n" +
                "cwm\n" +
                "jdwceh\n" +
                "\n" +
                "ekfyibdncovguazhjr\n" +
                "jkhgzbaoyidunvfr\n" +
                "vyaihouznrkgjbfd\n" +
                "xghojvrbdnzfuyaki\n" +
                "\n" +
                "jpgqlhvyi\n" +
                "pqihag\n" +
                "hqpig\n" +
                "gupqhi\n" +
                "ghqip\n" +
                "\n" +
                "glatmnqesbiwzkhup\n" +
                "jykuqrbswnmvocx\n" +
                "\n" +
                "ykqwxpjgcshtdbau\n" +
                "dfxqwpgbjcstkyua\n" +
                "xsgatjcbkwdyqup\n" +
                "usqykjpbgxdcwat\n" +
                "\n" +
                "cmevolpwiq\n" +
                "moagpqevltjiw\n" +
                "fmwziqbpuvleko\n" +
                "djvspewmohiql\n" +
                "\n" +
                "mdux\n" +
                "xmkud\n" +
                "xmdu\n" +
                "\n" +
                "vptyrkjxhcmounzgaw\n" +
                "wkmranuoxcjhslzytdigq\n" +
                "mjcazrxkguwfhbtnoy\n" +
                "\n" +
                "e\n" +
                "z\n" +
                "mr\n" +
                "e\n" +
                "\n" +
                "vrqek\n" +
                "kevrq\n" +
                "\n" +
                "wb\n" +
                "vcti\n" +
                "hyar\n" +
                "\n" +
                "e\n" +
                "e\n" +
                "\n" +
                "chqesv\n" +
                "vesqch\n" +
                "eqhvcs\n" +
                "\n" +
                "uae\n" +
                "xzecw\n" +
                "eyl\n" +
                "\n" +
                "bkgftdhvn\n" +
                "nbfkgdtvhj\n" +
                "nhftvgpkdb\n" +
                "\n" +
                "fwxkbouizcyjg\n" +
                "kwfqjgcyxzou\n" +
                "gfkdoytrjpczuwx\n" +
                "gyjvzcxfuowk\n" +
                "mxcjzsnuaefowyhlkg\n" +
                "\n" +
                "itwzbp\n" +
                "yhnafe\n" +
                "\n" +
                "dtnzjkibprafm\n" +
                "fnarjbkiptzdm\n" +
                "njrtpifmkbdaze\n" +
                "qkndmpaufbrjtiwzx\n" +
                "\n" +
                "eknujdxzmytriao\n" +
                "erkujinftzq\n" +
                "eskumatjicdnryz\n" +
                "\n" +
                "lvzhmxewbgnkuorypfai\n" +
                "ibnwkrfogvhaezxumpyl\n" +
                "hvbarmnowygqizujxplkef\n" +
                "hegopvnwrfybamkluxiz\n" +
                "\n" +
                "rdylnbotpv\n" +
                "raugkqfelbnwy\n" +
                "\n" +
                "vk\n" +
                "gnuypkw\n" +
                "kvj\n" +
                "kjh\n" +
                "\n" +
                "uprylxio\n" +
                "luixrp\n" +
                "ruxplki\n" +
                "\n" +
                "u\n" +
                "gmu\n" +
                "\n" +
                "ugbqne\n" +
                "ykvzwr\n" +
                "i\n" +
                "\n" +
                "vcqosrjbuxtl\n" +
                "hovtxlrbcqsu\n" +
                "bequwsltvxco\n" +
                "vxarnqstcbuzlo\n" +
                "cvuxqpobtsjl\n" +
                "\n" +
                "ctviybroekm\n" +
                "cyrtbevimok\n" +
                "tvokrbciyme\n" +
                "ekctbyvmoir\n" +
                "tymcviebokr\n" +
                "\n" +
                "sdmkxgfhjlpyba\n" +
                "puaowzsdqthkle\n" +
                "zwredloshkpca\n" +
                "\n" +
                "fjxo\n" +
                "joxf\n" +
                "fjxo\n" +
                "jfxo\n" +
                "fxoj\n" +
                "\n" +
                "mrqtv\n" +
                "rvqtwfm\n" +
                "rqmnvt\n" +
                "wmrvtq\n" +
                "qrftvm\n" +
                "\n" +
                "qwtjlfobuydncgzheisxr\n" +
                "qwxdlcuhjbnemaorpgfyzist\n" +
                "\n" +
                "zenwdhikljm\n" +
                "nejlmiwzkdh\n" +
                "jndelhwzkbmi\n" +
                "zelhwnijkdm\n" +
                "\n" +
                "jofdgmy\n" +
                "ojqdpbfg\n" +
                "gduojf\n" +
                "\n" +
                "awsgplcxqu\n" +
                "mulxgapdcjqk\n" +
                "acqjhfldpxgu\n" +
                "xluqipvbngact\n" +
                "\n" +
                "scdzqhyfplnx\n" +
                "nxkygdjuzbcqsmvt\n" +
                "zlxsqwnpdcay\n" +
                "czsxnrqyold\n" +
                "\n" +
                "qzvlitw\n" +
                "njapdb\n" +
                "xkbcf\n" +
                "uaogk\n" +
                "\n" +
                "ok\n" +
                "e\n" +
                "iu\n" +
                "\n" +
                "qshidleorzbgjnvpuckyawt\n" +
                "piojqrtzbnaukgwvchlesd\n" +
                "gduvqkcnhioepstrljwbza\n" +
                "qhripvstdjznlbgwuocake\n" +
                "jevrwsibcqlnutgkohdapz\n" +
                "\n" +
                "upcealv\n" +
                "gmpeyv\n" +
                "pve\n" +
                "lpkuevz\n" +
                "\n" +
                "pbtldk\n" +
                "bpqhdk\n" +
                "cibzd\n" +
                "\n" +
                "lk\n" +
                "hs\n" +
                "kx\n" +
                "l\n" +
                "\n" +
                "fkuirx\n" +
                "sy\n" +
                "zgqw\n" +
                "qmv\n" +
                "qv\n" +
                "\n" +
                "gdrtbwcjlhmqk\n" +
                "akdlqzjhctgm\n" +
                "dchqomkjylaftg\n" +
                "\n" +
                "vwal\n" +
                "ficwjzusyom\n" +
                "lw\n" +
                "\n" +
                "z\n" +
                "jyxo\n" +
                "n\n" +
                "\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "twxs\n" +
                "ox\n" +
                "\n" +
                "jzhaxuflebqwsipgctr\n" +
                "mgawzjihxrpcuesfbqtl\n" +
                "rljqhausvigxtofwczpbe\n" +
                "ifwjsdcbztphlxqrkeuag\n" +
                "hizafygceblrquxwtnsjp\n" +
                "\n" +
                "ioamx\n" +
                "xiaomg\n" +
                "oxami\n" +
                "axoim\n" +
                "amibxo\n" +
                "\n" +
                "dxgwsbmlnyqruckezp\n" +
                "xlurgtqncpwyfbisdkejm\n" +
                "\n" +
                "vflkdqcxbzuwmengty\n" +
                "swdbuexzlqvgmf\n" +
                "\n" +
                "ehsmravbk\n" +
                "ehmvrkadb\n" +
                "\n" +
                "qh\n" +
                "hq\n" +
                "thqx\n" +
                "qh\n" +
                "\n" +
                "uhi\n" +
                "aui\n" +
                "ui\n" +
                "iu\n" +
                "iu\n" +
                "\n" +
                "wlrnmb\n" +
                "yblnpr\n" +
                "bztijfenkola\n" +
                "\n" +
                "y\n" +
                "fgzyvds\n" +
                "yoj\n" +
                "iyp\n" +
                "\n" +
                "ohbiqfxzp\n" +
                "fpqihobx\n" +
                "xhoeiqbfp\n" +
                "\n" +
                "cgfi\n" +
                "figc\n" +
                "fgci\n" +
                "cflgi\n" +
                "cihgfnv\n" +
                "\n" +
                "vytbdxlzuwarjphnogic\n" +
                "gexwbnqfizmhtdjyrcolas\n" +
                "\n" +
                "hdeowrivjq\n" +
                "uzihgmjwxrve\n" +
                "wijeorhlqdsuv\n" +
                "ryeitfhvjw\n" +
                "ejhawvnuir\n" +
                "\n" +
                "siaxlobjmkvcwhernytfugd\n" +
                "rmtfsolejkdxihgvbnwcyua\n" +
                "oxglvkinrcebswamujfhtdy\n" +
                "gwsatohiknljburmdycevxf\n" +
                "cwuzdbgnethrvysmxolfkaji\n" +
                "\n" +
                "m\n" +
                "gm\n" +
                "bhslre\n" +
                "\n" +
                "xonqwkzcfbmtidpyvlsheu\n" +
                "pylzcoxmvqkehdsnftubjwi\n" +
                "nworbkczxutyedsvqfhimpl\n" +
                "\n" +
                "uatwvlgknhrfoqi\n" +
                "nwhbtokfiq\n" +
                "seniqpdzfhxmcotyw\n" +
                "utoiqafwhn\n" +
                "nqtoifwjh\n" +
                "\n" +
                "oxiflw\n" +
                "hflwxo\n" +
                "loxwbf\n" +
                "\n" +
                "mbt\n" +
                "tbm\n" +
                "\n" +
                "ocjflngrdakuypqiwxstzhmvbe\n" +
                "ykdaueiczwglbtrhjqnmsfxovp\n" +
                "\n" +
                "wtlzyrcomasqnjude\n" +
                "owhqdnmkzrpjlsxc\n" +
                "loqdmszxgvrjwcn\n" +
                "\n" +
                "on\n" +
                "x\n" +
                "x\n" +
                "\n" +
                "lbeyqfxkwm\n" +
                "jmqnfxbgwde\n" +
                "oezbufqrtm\n" +
                "\n" +
                "d\n" +
                "y\n" +
                "y\n" +
                "ta\n" +
                "\n" +
                "z\n" +
                "p\n" +
                "\n" +
                "fyx\n" +
                "xfiy\n" +
                "fxyw\n" +
                "xdfcy\n" +
                "fyx\n" +
                "\n" +
                "csjxkozmnl\n" +
                "slomjxkzc\n" +
                "\n" +
                "hqwadymfsbtlxv\n" +
                "kdvbatlfshwqmxy\n" +
                "lyahsxmqfwdtbvz\n" +
                "wxmlyahfdstvqb\n" +
                "tvqdsxfynlhamwb\n" +
                "\n" +
                "ojmvurikheablq\n" +
                "ukidqhvaljobe\n" +
                "\n" +
                "imc\n" +
                "tdkjmp\n" +
                "mi\n" +
                "\n" +
                "eq\n" +
                "eq\n" +
                "\n" +
                "thgulyifqobdwvecmarsjnp\n" +
                "ndlygcmjahefquiswbrptvo\n" +
                "\n" +
                "sjnptmdrlc\n" +
                "uvebzmlodrncp\n" +
                "lmypxkcfrnsd\n" +
                "cnmhdlqxiarwpg\n" +
                "\n" +
                "nzvqlh\n" +
                "hlzvn\n" +
                "lzhnv\n" +
                "\n" +
                "juq\n" +
                "ju\n" +
                "uj\n" +
                "\n" +
                "tjqiucmynvozxh\n" +
                "kmdvwafrxtq\n" +
                "exgqmtv\n" +
                "ftsqxmv\n" +
                "qklbtmxva\n" +
                "\n" +
                "r\n" +
                "r\n" +
                "pj\n" +
                "\n" +
                "pkoy\n" +
                "ypok\n" +
                "kypo\n" +
                "okyp\n" +
                "\n" +
                "f\n" +
                "fl\n" +
                "f\n" +
                "f\n" +
                "f\n" +
                "\n" +
                "snvqdyx\n" +
                "tdsxvnqy\n" +
                "deqynxsv\n" +
                "dnsxqvy\n" +
                "\n" +
                "lzhopfimuretwvd\n" +
                "jqgbvakrds\n" +
                "\n" +
                "zfbocen\n" +
                "mzbnacu\n" +
                "\n" +
                "ezyxtajrv\n" +
                "wzjuxreatv\n" +
                "\n" +
                "mrsejiyuvfz\n" +
                "jkuctbxpoiw\n" +
                "\n" +
                "nyvefxqicbah\n" +
                "brgeyltxvik\n" +
                "kyuvilexbs\n" +
                "ztvixyepb\n" +
                "pxiygvbe\n" +
                "\n" +
                "nadq\n" +
                "nyt\n" +
                "\n" +
                "prmt\n" +
                "ysjqkmocznhda\n" +
                "gmlibeu\n" +
                "bxmvf\n" +
                "\n" +
                "rm\n" +
                "wm\n" +
                "m\n" +
                "m\n" +
                "\n" +
                "wyfjzdlvcgreb\n" +
                "emlxnkpfjav\n" +
                "elijupnfvh\n" +
                "\n" +
                "pybv\n" +
                "bpvy\n" +
                "yrbvp\n" +
                "\n" +
                "zrjkxshpufec\n" +
                "vindgwtqbl\n" +
                "\n" +
                "ngmtqzfcpudhw\n" +
                "tphzgcwnqdfmu\n" +
                "ftzgphnmcudqw\n" +
                "quzpmctfngdwh\n" +
                "gqpdhufwcmtzn\n" +
                "\n" +
                "szfcnb\n" +
                "fczns\n" +
                "fnzcbsg\n" +
                "sznvafck\n" +
                "\n" +
                "arcezgin\n" +
                "egcirazn\n" +
                "gezcrian\n" +
                "icgnraez\n" +
                "\n" +
                "hgqucfnt\n" +
                "gqnukt\n" +
                "qgncut\n" +
                "tuqnhg\n" +
                "unfgqit\n" +
                "\n" +
                "w\n" +
                "setbdgv\n" +
                "\n" +
                "lck\n" +
                "lxk\n" +
                "kcl\n" +
                "kl\n" +
                "\n" +
                "emaqhxorctykufp\n" +
                "tigjzqhv\n" +
                "\n" +
                "mlvow\n" +
                "jqwo\n" +
                "ghksnruxipoac\n" +
                "\n" +
                "hxnpeqt\n" +
                "htzen\n" +
                "nhte\n" +
                "pchtne\n" +
                "\n" +
                "ehovjgfzaql\n" +
                "qhazvjlgeof\n" +
                "kfgljqhavzoe\n" +
                "jvlzfhgoeqa\n" +
                "veolzqfjgah\n" +
                "\n" +
                "bdlitrzuwh\n" +
                "epfmuhgvstibr";

        String[] inputArray = inputString.split("\n\n");

        int total = 0;

        for (String group : inputArray) {
            Character[] chars = group
                    .chars()
                    .mapToObj(c -> (char) c)
                    .toArray(Character[]::new);

            Set<Character> uniqueAnswers = new HashSet<>(Arrays.asList(chars));

            total += uniqueAnswers
                    .stream()
                    .filter(c -> c != '\n')
                    .count();
        }

        System.out.println(total);
    }
}
